language: node_js
node_js:
- "12.18.4"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version


script:
- node_modules/.bin/newman run tests/InternetPlatform.postman_collection.json -e tests/DEV.postman_environment.json
- node_modules/.bin/newman run tests/InternetPlatform.postman_collection.json -e tests/Production.postman_environment.json
